apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
        - image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-444811/imageregister/auth-ms
          name: auth-ms
          env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats:4222"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: DATABASE_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: JWT_SECRET
          resources: {}
status: {}

