apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/tienda-microservicios-444811/imageregister/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats:4222"
        - name: STRIPE_SUCCESS_URL  
          value: "http://localhost:3000/payments/success"
        - name: STRIPE_CANCEL_URL 
          value: "http://localhost:3000/payments/cancel"
        - name: STRIPE_SECRET
          valueFrom: 
            secretKeyRef:
              name: payments-secret
              key: STRIPE_SECRET
        - name: STRIPE_ENDPOIRNT_SECRET
          valueFrom: 
            secretKeyRef:
              name: payments-secret
              key: STRIPE_ENDPOIRNT_SECRET
        resources: {}
status: {}
